# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_in',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
